docs-erp/docs/readthedocs/gold/urls.py
"""Gold subscription URLs"""

from __future__ import absolute_import
from django.conf.urls import url

from readthedocs.gold import views
from readthedocs.projects.constants import PROJECT_SLUG_REGEX


urlpatterns = [
    url(r'^$', views.DetailGoldSubscription.as_view(), name='gold_detail'),
    url(r'^subscription/$', views.UpdateGoldSubscription.as_view(),
        name='gold_subscription'),
    url(r'^cancel/$', views.DeleteGoldSubscription.as_view(), name='gold_cancel'),
    url(r'^projects/$', views.projects, name='gold_projects'),
    url((r'^projects/remove/(?P<project_slug>{project_slug})/$'
         .format(project_slug=PROJECT_SLUG_REGEX)),
        views.projects_remove,
        name='gold_projects_remove'),
]

docs-erp/readthedocs/gold/urls.py
"""Gold subscription URLs"""

from __future__ import absolute_import
from django.conf.urls import url

from readthedocs.gold import views
from readthedocs.projects.constants import PROJECT_SLUG_REGEX


urlpatterns = [
    url(r'^$', views.DetailGoldSubscription.as_view(), name='gold_detail'),
    url(r'^subscription/$', views.UpdateGoldSubscription.as_view(),
        name='gold_subscription'),
    url(r'^cancel/$', views.DeleteGoldSubscription.as_view(), name='gold_cancel'),
    url(r'^projects/$', views.projects, name='gold_projects'),
    url((r'^projects/remove/(?P<project_slug>{project_slug})/$'
         .format(project_slug=PROJECT_SLUG_REGEX)),
        views.projects_remove,
        name='gold_projects_remove'),
]

docs-erp/readthedocs/urls.py
# pylint: disable=missing-docstring
from __future__ import absolute_import

from functools import reduce
from operator import add

from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import TemplateView
from tastypie.api import Api

from readthedocs.api.base import (ProjectResource, UserResource,
                                  VersionResource, FileResource)
from readthedocs.core.urls import docs_urls, core_urls, deprecated_urls
from readthedocs.core.views import (HomepageView, SupportView,
                                    server_error_404, server_error_500)
from readthedocs.search import views as search_views


v1_api = Api(api_name='v1')
v1_api.register(UserResource())
v1_api.register(ProjectResource())
v1_api.register(VersionResource())
v1_api.register(FileResource())

admin.autodiscover()

handler404 = server_error_404
handler500 = server_error_500

basic_urls = [
    url(r'^$', HomepageView.as_view(), name='homepage'),
    url(r'^support/', SupportView.as_view(), name='support'),
    url(r'^security/', TemplateView.as_view(template_name='security.html')),
]

rtd_urls = [
    url(r'^bookmarks/', include('readthedocs.bookmarks.urls')),
    url(r'^search/$', search_views.elastic_search, name='search'),
    url(r'^dashboard/', include('readthedocs.projects.urls.private')),
    url(r'^profiles/', include('readthedocs.profiles.urls.public')),
    url(r'^accounts/', include('readthedocs.profiles.urls.private')),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^notifications/', include('readthedocs.notifications.urls')),
    # For redirects
    url(r'^builds/', include('readthedocs.builds.urls')),
    # For testing the 404's with DEBUG on.
    url(r'^404/$', handler404),
    # For testing the 500's with DEBUG on.
    url(r'^500/$', handler500),
]

project_urls = [
    url(r'^projects/', include('readthedocs.projects.urls.public')),
]

api_urls = [
    url(r'^api/', include(v1_api.urls)),
    url(r'^api/v2/', include('readthedocs.restapi.urls')),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^websupport/', include('readthedocs.comments.urls')),
]

i18n_urls = [
    url(r'^i18n/', include('django.conf.urls.i18n')),
]

admin_urls = [
    url(r'^admin/', include(admin.site.urls)),
]

debug_urls = add(
    [
        url('style-catalog/$',
            TemplateView.as_view(template_name='style_catalog.html')),
    ],
    static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
)

# Export URLs
groups = [basic_urls, rtd_urls, project_urls, api_urls, core_urls, i18n_urls,
          deprecated_urls]

if 'readthedocs.donate' in settings.INSTALLED_APPS:
    # Include donation URL's
    groups.append([
        url(r'^sustainability/', include('readthedocs.donate.urls')),
        url(r'^accounts/gold/', include('readthedocs.gold.urls')),
    ])
if not getattr(settings, 'USE_SUBDOMAIN', False) or settings.DEBUG:
    groups.insert(0, docs_urls)
if getattr(settings, 'ALLOW_ADMIN', True):
    groups.append(admin_urls)
if getattr(settings, 'DEBUG', False):
    groups.append(debug_urls)

urlpatterns = reduce(add, groups)

docs-erp/docs/readthedocs/gold/models.py
"""Django models for recurring donations aka Gold Membership."""
from __future__ import absolute_import
from __future__ import division
from past.utils import old_div
import math

from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext_lazy as _

from readthedocs.projects.models import Project


#: The membership options that are currently available
LEVEL_CHOICES = (
    ('v1-org-5', '$5/mo'),
    ('v1-org-10', '$10/mo'),
    ('v1-org-15', '$15/mo'),
    ('v1-org-20', '$20/mo'),
    ('v1-org-50', '$50/mo'),
    ('v1-org-100', '$100/mo'),
)

#: An estimate of the cost of supporting one project for a month
DOLLARS_PER_PROJECT = 5


@python_2_unicode_compatible
class GoldUser(models.Model):

    """A user subscription for gold membership."""

    pub_date = models.DateTimeField(_('Publication date'), auto_now_add=True)
    modified_date = models.DateTimeField(_('Modified date'), auto_now=True)

    user = models.ForeignKey('auth.User', verbose_name=_('User'), unique=True, related_name='gold')
    level = models.CharField(_('Level'), max_length=20,
                             choices=LEVEL_CHOICES, default=LEVEL_CHOICES[0][0])
    projects = models.ManyToManyField(Project, verbose_name=_('Projects'),
                                      related_name='gold_owners')

    last_4_digits = models.CharField(max_length=4)
    stripe_id = models.CharField(max_length=255)
    subscribed = models.BooleanField(default=False)

    def __str__(self):
        return 'Gold Level %s for %s' % (self.level, self.user)

    @property
    def num_supported_projects(self):
        dollars = int(self.level.split('-')[-1])
        num_projects = int(math.floor(old_div(dollars, DOLLARS_PER_PROJECT)))
        return num_projects

docs-erp/docs/readthedocs/gold/forms.py
"""Gold subscription forms"""

from __future__ import absolute_import
from builtins import object
from django import forms

from stripe.error import InvalidRequestError
from readthedocs.payments.forms import StripeModelForm, StripeResourceMixin

from .models import LEVEL_CHOICES, GoldUser


class GoldSubscriptionForm(StripeResourceMixin, StripeModelForm):

    """Gold subscription payment form

    This extends the common base form for handling Stripe subscriptions. Credit
    card fields for card number, expiry, and CVV are extended from
    :py:class:`StripeModelForm`, with additional methods from
    :py:class:`StripeResourceMixin` for common operations against the Stripe API.
    """

    class Meta(object):
        model = GoldUser
        fields = ['last_4_digits', 'level']

    last_4_digits = forms.CharField(
        required=True,
        min_length=4,
        max_length=4,
        widget=forms.HiddenInput(attrs={
            'data-bind': 'valueInit: card_digits, value: card_digits'
        })
    )

    level = forms.ChoiceField(
        required=True,
        choices=LEVEL_CHOICES,
    )

    def clean(self):
        self.instance.user = self.customer
        return super(GoldSubscriptionForm, self).clean()

    def validate_stripe(self):
        subscription = self.get_subscription()
        self.instance.stripe_id = subscription.customer
        self.instance.subscribed = True

    def get_customer_kwargs(self):
        return {
            'description': self.customer.get_full_name() or self.customer.username,
            'email': self.customer.email,
            'id': self.instance.stripe_id or None
        }

    def get_subscription(self):
        customer = self.get_customer()
        try:
            # TODO get the first sub more intelligently
            subscriptions = customer.subscriptions.all(limit=5)
            subscription = subscriptions.data[0]
            subscription.plan = self.cleaned_data['level']
            if 'stripe_token' in self.cleaned_data:
                subscription.source = self.cleaned_data['stripe_token']
            subscription.save()
            return subscription
        except (InvalidRequestError, AttributeError, IndexError):
            subscription = customer.subscriptions.create(
                plan=self.cleaned_data['level'],
                source=self.cleaned_data['stripe_token']
            )
            return subscription

    def clear_card_data(self):
        super(GoldSubscriptionForm, self).clear_card_data()
        self.data['last_4_digits'] = None


class GoldProjectForm(forms.Form):
    project = forms.CharField(
        required=True,
    )

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        self.projects = kwargs.pop('projects', None)
        super(GoldProjectForm, self).__init__(*args, **kwargs)

    def clean(self):
        cleaned_data = super(GoldProjectForm, self).clean()
        if self.projects.count() < self.user.num_supported_projects:
            return cleaned_data
        else:
            self.add_error(None, 'You already have the max number of supported projects.')

docs-erp/docs/readthedocs/gold/views.py
"""Gold subscription views"""

from __future__ import absolute_import
from django.core.urlresolvers import reverse, reverse_lazy
from django.conf import settings
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.shortcuts import render_to_response, get_object_or_404
from django.template import RequestContext
from django.contrib.auth.decorators import login_required
from django.utils.translation import ugettext_lazy as _
from vanilla import DeleteView, UpdateView, DetailView

from readthedocs.core.mixins import LoginRequiredMixin
from readthedocs.projects.models import Project, Domain
from readthedocs.payments.mixins import StripeMixin

from .forms import GoldSubscriptionForm, GoldProjectForm
from .models import GoldUser


class GoldSubscriptionMixin(SuccessMessageMixin, StripeMixin, LoginRequiredMixin):

    """Gold subscription mixin for view classes"""

    model = GoldUser
    form_class = GoldSubscriptionForm

    def get_object(self):
        try:
            return self.get_queryset().get(user=self.request.user)
        except self.model.DoesNotExist:
            return None

    def get_form(self, data=None, files=None, **kwargs):
        """Pass in copy of POST data to avoid read only QueryDicts"""
        kwargs['customer'] = self.request.user
        return super(GoldSubscriptionMixin, self).get_form(data, files, **kwargs)

    def get_success_url(self, **__):
        return reverse_lazy('gold_detail')

    def get_template_names(self):
        return ('gold/subscription{0}.html'
                .format(self.template_name_suffix))

    def get_context_data(self, **kwargs):
        context = super(GoldSubscriptionMixin, self).get_context_data(**kwargs)
        domains = Domain.objects.filter(project__users=self.request.user)
        context['domains'] = domains
        return context

# Subscription Views


class DetailGoldSubscription(GoldSubscriptionMixin, DetailView):

    def get(self, request, *args, **kwargs):
        """GET handling for this view

        If there is a gold subscription instance, then we show the normal detail
        page, otherwise show the registration form
        """
        resp = super(DetailGoldSubscription, self).get(request, *args, **kwargs)
        if self.object is None:
            return HttpResponseRedirect(reverse('gold_subscription'))
        return resp


class UpdateGoldSubscription(GoldSubscriptionMixin, UpdateView):
    success_message = _('Your subscription has been updated')


class DeleteGoldSubscription(GoldSubscriptionMixin, DeleteView):

    """Delete Gold subscription view

    On object deletion, the corresponding Stripe customer is deleted as well.
    Deletion is triggered on subscription deletion using a signal, ensuring the
    subscription is synced with Stripe.
    """

    success_message = _('Your subscription has been cancelled')

    def post(self, request, *args, **kwargs):
        """Add success message to delete post"""
        resp = super(DeleteGoldSubscription, self).post(request, *args, **kwargs)
        success_message = self.get_success_message({})
        if success_message:
            messages.success(self.request, success_message)
        return resp


@login_required
def projects(request):
    gold_user = get_object_or_404(GoldUser, user=request.user)
    gold_projects = gold_user.projects.all()

    if request.method == 'POST':
        form = GoldProjectForm(data=request.POST, user=gold_user, projects=gold_projects)
        if form.is_valid():
            to_add = Project.objects.get(slug=form.cleaned_data['project'])
            gold_user.projects.add(to_add)
            return HttpResponseRedirect(reverse('gold_projects'))
    else:
        form = GoldProjectForm()

    return render_to_response(
        'gold/projects.html',
        {
            'form': form,
            'gold_user': gold_user,
            'publishable': settings.STRIPE_PUBLISHABLE,
            'user': request.user,
            'projects': gold_projects
        },
        context_instance=RequestContext(request)
    )


@login_required
def projects_remove(request, project_slug):
    gold_user = get_object_or_404(GoldUser, user=request.user)
    project = get_object_or_404(Project.objects.all(), slug=project_slug)
    gold_user.projects.remove(project)
    return HttpResponseRedirect(reverse('gold_projects'))

docs-erp/docs/readthedocs/projects/backends/views.py
"""
Project views loaded by configuration settings

Use these views instead of calling the views directly, in order to allow for
settings override of the view class.
"""

from __future__ import absolute_import
from readthedocs.core.utils.extend import SettingsOverrideObject
from readthedocs.projects.views import private


# Project Import Wizard
class ImportWizardView(SettingsOverrideObject):
    _default_class = private.ImportWizardView
    _override_setting = 'PROJECT_IMPORT_VIEW'


# Project demo import
class ImportDemoView(SettingsOverrideObject):
    _default_class = private.ImportDemoView
    _override_setting = 'PROJECT_IMPORT_DEMO_VIEW'

docs-erp/docs/readthedocs/projects/views/mixins.py
"""Mixin classes for project views"""

from __future__ import absolute_import
from builtins import object
from django.shortcuts import get_object_or_404

from readthedocs.projects.models import Project


class ProjectRelationMixin(object):

    """Mixin class for constructing model views for project dashboard

    This mixin class is used for model views on models that have a relation
    to the :py:cls:`Project` model.

    :cvar project_lookup_url_kwarg: URL kwarg to use in project lookup
    :cvar project_lookup_field: Query field for project relation
    :cvar project_context_object_name: Context object name for project
    """

    project_lookup_url_kwarg = 'project_slug'
    project_lookup_field = 'project'
    project_context_object_name = 'project'

    def get_project_queryset(self):
        return Project.objects.for_admin_user(user=self.request.user)

    def get_project(self):
        if self.project_lookup_url_kwarg not in self.kwargs:
            return None
        return get_object_or_404(
            self.get_project_queryset(),
            slug=self.kwargs[self.project_lookup_url_kwarg]
        )

    def get_queryset(self):
        return self.model.objects.filter(
            **{self.project_lookup_field: self.get_project()}
        )

    def get_context_data(self, **kwargs):
        context = super(ProjectRelationMixin, self).get_context_data(**kwargs)
        context[self.project_context_object_name] = self.get_project()
        return context

docs-erp/readthedocs/projects/backends/views.py
"""
Project views loaded by configuration settings

Use these views instead of calling the views directly, in order to allow for
settings override of the view class.
"""

from __future__ import absolute_import
from readthedocs.core.utils.extend import SettingsOverrideObject
from readthedocs.projects.views import private


# Project Import Wizard
class ImportWizardView(SettingsOverrideObject):
    _default_class = private.ImportWizardView
    _override_setting = 'PROJECT_IMPORT_VIEW'


# Project demo import
class ImportDemoView(SettingsOverrideObject):
    _default_class = private.ImportDemoView
    _override_setting = 'PROJECT_IMPORT_DEMO_VIEW'

docs-erp/readthedocs/gold/templates/gold/projects.html
{% extends "profiles/base_profile_edit.html" %}
{% load static %}
{% load i18n %}

{% block profile-admin-gold-edit %}active{% endblock %}

{% block title %}
Gold Projects
{% endblock %}

{% block extra_scripts %}
  <script type="text/javascript" src="{% static 'core/js/autocomplete.js' %}"></script>
  <script type="text/javascript">
var attach_project_autocomplete = require('core/autocomplete');
$(document).ready(function () {
  attach_project_autocomplete('#id_project', '{% url "search_autocomplete" %}');
});
  </script>
{% endblock %}

{% block edit_content %}

  <p class="help_text">
    {% trans "Choose projects that will have all promos removed, and extra features added to them. You get to pick one for every $5/mo you support Read the Docs with." %}
  </p>

  <h3> {% trans "Existing Projects" %} </h3>
  <p>
    {% blocktrans count projects=gold_user.num_supported_projects %}
      You can adopt one project with your subscription.
    {% plural %}
      You can adopt {{ projects }} projects with your subscription.
    {% endblocktrans %}
  </p>

    <ul>
    {% for project in projects %}
        <li>
        <a href="{{ project.get_absolute_url }}">
        {{ project }}
        </a>
        (<a href="{% url "gold_projects_remove" project.slug %}">{% trans "Remove" %}</a>)
        </li>
    {% endfor %}
    </ul>
  </p>

  <h3>{% trans "Add a project" %}</h3>
  <p>
    {% trans "Choose which project you would like to add." %}
  </p>
  <form method="post" action=".">{% csrf_token %}
    {{ form.as_p }}
    <p>
      <input style="display: inline;" type="submit" value="{% trans "Submit" %}">
    </p>
  </form>

{% endblock %}

docs-erp/readthedocs/gold/templates/gold/subscription_confirm_delete.html
{% extends "profiles/base_profile_edit.html" %}
{% load i18n %}

{% block profile-admin-gold-edit %}active{% endblock %}

{% block title %}Cancel Gold{% endblock %}

{% block edit_content %}
  <h2>Cancel Gold Subscription</h2>

  <p>
    {% blocktrans %}
      Are you sure you want to cancel your subscription?
    {% endblocktrans %}
  </p>

  <form  method="post" action="{% url "gold_cancel" %}">
    {% csrf_token %}
    <input type="submit" value="{% trans "Cancel Subscription" %}">
  </form>
{% endblock %}

docs-erp/readthedocs/gold/templates/gold/subscription_detail.html
{% extends "profiles/base_profile_edit.html" %}
{% load static %}
{% load i18n %}

{% block profile-admin-gold-edit %}active{% endblock %}

{% block title %}{% trans "Gold Subscription" %}{% endblock %}

{% block extra_scripts %}
  <script src="https://js.stripe.com/v2/" type="text/javascript"></script>
  <script type="text/javascript" src="{% static 'vendor/knockout.js' %}"></script>
  <script type="text/javascript" src="{% static 'gold/js/gold.js' %}"></script>
  <script type="text/javascript">
var gold_views = require('gold/gold');
$(document).ready(function () {
    var key;
    //<![CDATA[
    key = '{{ publishable }}';
    //]]>

    var view = gold_views.GoldView.init({
      key: key,
      form: $('form#gold-register')
    });
});
  </script>
{% endblock %}

{% block edit_content %}
  <div class="gold-subscription">
    <h2>{% trans "Gold Subscription" %}</h2>

    <p>
      {% blocktrans %}
        Thanks for supporting Read the Docs! It really means a lot to us.
      {% endblocktrans %}
    </p>

    <p class="subscription-detail subscription-detail-level">
      <label>{% trans "Level" %}:</label>
      <span>{{ golduser.get_level_display }}</span>
    </p>

    <p class="subscription-detail subscription-detail-card">
      <label>{% trans "Card" %}:</label>
      <span>****-{{ golduser.last_4_digits }}</span>
    </p>

    <form method="get" action="{% url "gold_subscription" %}" class="subscription-update">
      <button>{% trans "Update Subscription" %}</button>
    </form>

    <form method="get" action="{% url "gold_cancel" %}" class="subscription-cancel">
      <button>{% trans "Cancel Subscription" %}</button>
    </form>

    <h3>{% trans "Projects" %}</h3>
    <p class="subscription-projects">
      {% blocktrans count projects=golduser.num_supported_projects %}
        You can adopt one project with your subscription.
      {% plural %}
        You can adopt {{ projects }} projects with your subscription.
      {% endblocktrans %}
    </p>

    <form method="get" action="{% url "gold_projects" %}" class="subscription-projects">
      <button>{% trans "Select Projects" %}</button>
    </form>
  </div>
{% endblock %}

docs-erp/readthedocs/gold/templates/gold/subscription_form.html
{% extends "profiles/base_profile_edit.html" %}
{% load static %}
{% load i18n %}

{% block profile-admin-gold-edit %}active{% endblock %}

{% block title %}
Read the Docs Gold
{% endblock %}

{% block extra_links %}
  <link rel="stylesheet" href="{% static 'payments/css/form.css' %}" />
{% endblock %}

{% block extra_scripts %}
  <script src="https://js.stripe.com/v2/" type="text/javascript"></script>
  <script type="text/javascript" src="{% static 'vendor/knockout.js' %}"></script>
  <script type="text/javascript" src="{% static 'gold/js/gold.js' %}"></script>
  <script type="text/javascript">
var gold_views = require('gold/gold');
$(document).ready(function () {
    var key;
    //<![CDATA[
    key = '{{ stripe_publishable }}';
    //]]>

    var view = gold_views.GoldView.init({
      key: key,
      form: $('form#gold-register')
    });
});
  </script>
{% endblock %}

{% block edit_content %}
<div>
  <h2>Read the Docs Gold</h2>

  <p>
    {% blocktrans %}
      Supporting Read the Docs lets us work more on features that people love.
      Your money will go directly to maintenance and development of the
      product.
    {% endblocktrans %}
  </p>
    <p>
    {% blocktrans %}
      If you are an individual,
      feel free to give whatever feels right for the value you get out of Read the Docs.
    {% endblocktrans %}
    </p>
    <p>
    {% blocktrans %}
      If you are a company using Read the Docs,
      please consider getting a <a href="https://readthedocs.com/services/#open-source-support">commercial support contract</a>.
      This will help us cover our costs,
      and provide you with a better experience on the site.
      If you aren't able to do that,
      we suggest giving at least $20/month to help cover our support and operations costs.
    {% endblocktrans %}
    </p>
  <p>
    {% blocktrans %}
      You can also make one-time donations on our <a href="https://readthedocs.org/sustainability/">sustainability</a> page.
    {% endblocktrans %}
  </p>

  {% if domains.count %}
  <h3>Domains</h2>
  <p>
    {% blocktrans %}
    We ask that folks who use custom Domains give Read the Docs $5 per domain they are using.
    This is optional, but it really does help us maintain the site going forward.
    {% endblocktrans %}
  </p>

  <p>
    You are currently using {{ domains.count }} domains:
    
    <ul class="donate-about">
    {% for domain in domains %}
      <li>{{ domain.domain }} ({{ domain.project.name }})</li>
    {% endfor %}
    </ul>
  </p>

  {% endif %}

  {% trans "Become a Gold Member" as subscription_title %}
  {% if golduser %}
    {% trans "Update Your Subscription" as subscription_title %}
  {% endif %}
  <h3>{{ subscription_title }}</h3>

  <form accept-charset="UTF-8" action="" method="post" id="gold-register" class="payment">
    {% csrf_token %}

    {{ form.non_field_errors }}

    {% for field in form.fields_with_cc_group %}
      {% if field.is_cc_group %}
        <p
            data-bind="visible: card_digits"
            style="display: none;"
            class="subscription-card">
          <label>{% trans "Current card" %}:</label>
          <span class="subscription-card-number">
            ****-<span data-bind="text: card_digits"></span>
          </span>
        </p>

        <div data-bind="visible: !show_card_form()">
          <a
              href="#"
              data-bind="click: function () { is_editing_card(true); }"
              class="subscription-edit-link">
            {% trans "Edit Card" %}
          </a>
        </div>
        <div
            class="subscription-card"
            data-bind="visible: show_card_form"
            style="display: none;">
          {% for groupfield in field.fields %}
            {% include 'core/ko_form_field.html' with field=groupfield %}
          {% endfor %}
        </div>
      {% else %}
        {% include 'core/ko_form_field.html' with field=field %}
      {% endif %}
    {% endfor %}

    {% trans "Sign Up" as form_submit_text %}
    {% if golduser %}
      {% trans "Update Subscription" as form_submit_text %}
    {% endif %}
    <input type="submit" value="{{ form_submit_text }}" data-bind="click: process_full_form" />

    <em>{% trans "All information is submitted directly to Stripe." %}</em>
  </form>
{% endblock %}