docs-erp/docs/readthedocs/donate/urls.py
"""Django URL patterns for the donate app."""

from __future__ import absolute_import
from django.conf.urls import url

from .views import DonateCreateView, DonateListView, DonateSuccessView
from .views import PayAdsView, PaySuccess, PromoDetailView
from .views import click_proxy, view_proxy


urlpatterns = [
    url(r'^$', DonateListView.as_view(), name='donate'),
    url(r'^pay/$', PayAdsView.as_view(), name='pay_ads'),
    url(r'^pay/success/$', PaySuccess.as_view(), name='pay_success'),
    url(r'^report/(?P<promo_slug>.+)/$', PromoDetailView.as_view(), name='donate_promo_detail'),
    url(r'^contribute/$', DonateCreateView.as_view(), name='donate_add'),
    url(r'^contribute/thanks$', DonateSuccessView.as_view(), name='donate_success'),
    url(r'^view/(?P<promo_id>\d+)/(?P<hash>.+)/$', view_proxy, name='donate_view_proxy'),
    url(r'^click/(?P<promo_id>\d+)/(?P<hash>.+)/$', click_proxy, name='donate_click_proxy'),
]

docs-erp/readthedocs/donate/urls.py
"""Django URL patterns for the donate app."""

from __future__ import absolute_import
from django.conf.urls import url

from .views import DonateCreateView, DonateListView, DonateSuccessView
from .views import PayAdsView, PaySuccess, PromoDetailView
from .views import click_proxy, view_proxy


urlpatterns = [
    url(r'^$', DonateListView.as_view(), name='donate'),
    url(r'^pay/$', PayAdsView.as_view(), name='pay_ads'),
    url(r'^pay/success/$', PaySuccess.as_view(), name='pay_success'),
    url(r'^report/(?P<promo_slug>.+)/$', PromoDetailView.as_view(), name='donate_promo_detail'),
    url(r'^contribute/$', DonateCreateView.as_view(), name='donate_add'),
    url(r'^contribute/thanks$', DonateSuccessView.as_view(), name='donate_success'),
    url(r'^view/(?P<promo_id>\d+)/(?P<hash>.+)/$', view_proxy, name='donate_view_proxy'),
    url(r'^click/(?P<promo_id>\d+)/(?P<hash>.+)/$', click_proxy, name='donate_click_proxy'),
]

docs-erp/readthedocs/urls.py
# pylint: disable=missing-docstring
from __future__ import absolute_import

from functools import reduce
from operator import add

from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import TemplateView
from tastypie.api import Api

from readthedocs.api.base import (ProjectResource, UserResource,
                                  VersionResource, FileResource)
from readthedocs.core.urls import docs_urls, core_urls, deprecated_urls
from readthedocs.core.views import (HomepageView, SupportView,
                                    server_error_404, server_error_500)
from readthedocs.search import views as search_views


v1_api = Api(api_name='v1')
v1_api.register(UserResource())
v1_api.register(ProjectResource())
v1_api.register(VersionResource())
v1_api.register(FileResource())

admin.autodiscover()

handler404 = server_error_404
handler500 = server_error_500

basic_urls = [
    url(r'^$', HomepageView.as_view(), name='homepage'),
    url(r'^support/', SupportView.as_view(), name='support'),
    url(r'^security/', TemplateView.as_view(template_name='security.html')),
]

rtd_urls = [
    url(r'^bookmarks/', include('readthedocs.bookmarks.urls')),
    url(r'^search/$', search_views.elastic_search, name='search'),
    url(r'^dashboard/', include('readthedocs.projects.urls.private')),
    url(r'^profiles/', include('readthedocs.profiles.urls.public')),
    url(r'^accounts/', include('readthedocs.profiles.urls.private')),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^notifications/', include('readthedocs.notifications.urls')),
    # For redirects
    url(r'^builds/', include('readthedocs.builds.urls')),
    # For testing the 404's with DEBUG on.
    url(r'^404/$', handler404),
    # For testing the 500's with DEBUG on.
    url(r'^500/$', handler500),
]

project_urls = [
    url(r'^projects/', include('readthedocs.projects.urls.public')),
]

api_urls = [
    url(r'^api/', include(v1_api.urls)),
    url(r'^api/v2/', include('readthedocs.restapi.urls')),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^websupport/', include('readthedocs.comments.urls')),
]

i18n_urls = [
    url(r'^i18n/', include('django.conf.urls.i18n')),
]

admin_urls = [
    url(r'^admin/', include(admin.site.urls)),
]

debug_urls = add(
    [
        url('style-catalog/$',
            TemplateView.as_view(template_name='style_catalog.html')),
    ],
    static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
)

# Export URLs
groups = [basic_urls, rtd_urls, project_urls, api_urls, core_urls, i18n_urls,
          deprecated_urls]

if 'readthedocs.donate' in settings.INSTALLED_APPS:
    # Include donation URL's
    groups.append([
        url(r'^sustainability/', include('readthedocs.donate.urls')),
        url(r'^accounts/gold/', include('readthedocs.gold.urls')),
    ])
if not getattr(settings, 'USE_SUBDOMAIN', False) or settings.DEBUG:
    groups.insert(0, docs_urls)
if getattr(settings, 'ALLOW_ADMIN', True):
    groups.append(admin_urls)
if getattr(settings, 'DEBUG', False):
    groups.append(debug_urls)

urlpatterns = reduce(add, groups)

docs-erp/docs/readthedocs/donate/models.py
"""Django models for the donate app."""
# We use 'type' and 'hash' heavily in the API here.
# pylint: disable=redefined-builtin
from __future__ import (absolute_import, division)

from past.utils import old_div
from builtins import object
from django.db import models
from django.utils.crypto import get_random_string
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext_lazy as _, pgettext
from django.core.urlresolvers import reverse
from django.conf import settings
from django_countries.fields import CountryField
import six

from readthedocs.donate.utils import get_ad_day
from readthedocs.donate.constants import (
    DISPLAY_CHOICES, FILTER_CHOICES, IMPRESSION_TYPES, THEMES, READTHEDOCS_THEME
)
from readthedocs.projects.models import Project
from readthedocs.projects.constants import PROGRAMMING_LANGUAGES


@python_2_unicode_compatible
class Supporter(models.Model):
    pub_date = models.DateTimeField(_('Publication date'), auto_now_add=True)
    modified_date = models.DateTimeField(_('Modified date'), auto_now=True)
    public = models.BooleanField(_('Public'), default=True)

    name = models.CharField(_('name'), max_length=200, blank=True)
    email = models.EmailField(_('Email'), max_length=200, blank=True)
    user = models.ForeignKey('auth.User', verbose_name=_('User'),
                             related_name='goldonce', blank=True, null=True)
    dollars = models.IntegerField(_('Amount'), default=50)
    logo_url = models.URLField(_('Logo URL'), max_length=255, blank=True,
                               null=True)
    site_url = models.URLField(_('Site URL'), max_length=255, blank=True,
                               null=True)

    last_4_digits = models.CharField(max_length=4)
    stripe_id = models.CharField(max_length=255)
    subscribed = models.BooleanField(default=False)

    def __str__(self):
        return self.name


@python_2_unicode_compatible
class SupporterPromo(models.Model):

    """A banner advertisement."""

    pub_date = models.DateTimeField(_('Publication date'), auto_now_add=True)
    modified_date = models.DateTimeField(_('Modified date'), auto_now=True)

    name = models.CharField(_('Name'), max_length=200)
    analytics_id = models.CharField(_('Analytics ID'), max_length=200)
    text = models.TextField(_('Text'), blank=True)
    link = models.URLField(_('Link URL'), max_length=255, blank=True, null=True)
    image = models.URLField(_('Image URL'), max_length=255, blank=True, null=True)
    display_type = models.CharField(_('Display Type'), max_length=200,
                                    choices=DISPLAY_CHOICES, default='doc')
    sold_impressions = models.IntegerField(_('Sold Impressions'), default=1000000)
    sold_days = models.IntegerField(_('Sold Days'), default=30)
    sold_clicks = models.IntegerField(_('Sold Clicks'), default=0)
    programming_language = models.CharField(_('Programming Language'), max_length=20,
                                            choices=PROGRAMMING_LANGUAGES, default=None,
                                            blank=True, null=True)
    theme = models.CharField(_('Theme'), max_length=40,
                             choices=THEMES, default=READTHEDOCS_THEME,
                             blank=True, null=True)
    community = models.BooleanField(_('Community Ad'), default=False)
    live = models.BooleanField(_('Live'), default=False)

    class Meta(object):
        ordering = ('analytics_id', '-live')

    def __str__(self):
        return self.name

    def as_dict(self):
        """A dict respresentation of this for JSON encoding"""
        hash = get_random_string()
        domain = getattr(settings, 'PRODUCTION_DOMAIN', 'readthedocs.org')
        if self.image:
            image_url = '//{host}{url}'.format(
                host=domain,
                url=reverse(
                    'donate_view_proxy',
                    kwargs={'promo_id': self.pk, 'hash': hash}
                ))
        else:
            image_url = None
        # TODO: Store this hash and confirm that a proper hash was sent later
        link_url = '//{host}{url}'.format(
            host=domain,
            url=reverse(
                'donate_click_proxy',
                kwargs={'promo_id': self.pk, 'hash': hash}
            ))
        return {
            'id': self.analytics_id,
            'text': self.text,
            'link': link_url,
            'image': image_url,
            'hash': hash,
        }

    def cache_key(self, type, hash):
        assert type in IMPRESSION_TYPES + ('project',)
        return 'promo:{id}:{hash}:{type}'.format(id=self.analytics_id, hash=hash, type=type)

    def incr(self, type, project=None):
        """Add to the number of times this action has been performed, stored in the DB"""
        assert type in IMPRESSION_TYPES
        day = get_ad_day()
        if project:
            impression, _ = self.project_impressions.get_or_create(date=day, project=project)
        else:
            impression, _ = self.impressions.get_or_create(date=day)

        setattr(impression, type, models.F(type) + 1)
        impression.save()

        # TODO: Support redis, more info on this PR
        #
        # https://github.com/rtfd/readthedocs.org
        #     /pull/2105/files/1b5f8568ae0a7760f7247149bcff481efc000f32#r58253051

    def view_ratio(self, day=None):
        if not day:
            day = get_ad_day()
        impression = self.impressions.get_or_create(date=day)[0]
        return impression.view_ratio

    def click_ratio(self, day=None):
        if not day:
            day = get_ad_day()
        impression = self.impressions.get_or_create(date=day)[0]
        return impression.click_ratio

    def views_per_day(self):
        return int(old_div(float(self.sold_impressions), float(self.sold_days)))

    def views_shown_today(self, day=None):
        if not day:
            day = get_ad_day()
        impression = self.impressions.get_or_create(date=day)[0]
        return float(impression.views)

    def views_needed_today(self):
        ret = self.views_per_day() - self.views_shown_today()
        if ret < 0:
            return 0
        return ret

    def total_views(self):
        return sum(imp.views for imp in self.impressions.all())

    def total_clicks(self):
        return sum(imp.clicks for imp in self.impressions.all())

    def total_click_ratio(self):
        if self.total_views() == 0:
            return float(0)
        return '%.4f' % float(
            (old_div(float(self.total_clicks()), float(self.total_views()))) * 100
        )

    def report_html_text(self):
        """
        Include the link in the html text.

        Only used for reporting,
        doesn't include any click fraud protection!
        """
        return self.text.replace('<a>', "<a href='%s'>" % self.link)


class BaseImpression(models.Model):

    """Statistics for tracking."""

    date = models.DateField(_('Date'))
    offers = models.IntegerField(_('Offer'), default=0)
    views = models.IntegerField(
        pgettext('View', 'Number of display on a screen that were sold'), default=0)
    clicks = models.IntegerField(_('Clicks'), default=0)

    class Meta(object):
        ordering = ('-date',)
        unique_together = ('promo', 'date')
        abstract = True

    @property
    def view_ratio(self):
        if self.offers == 0:
            return 0  # Don't divide by 0
        return float(
            float(self.views) / float(self.offers) * 100
        )

    @property
    def click_ratio(self):
        if self.views == 0:
            return 0  # Don't divide by 0
        return '%.3f' % float(
            float(self.clicks) / float(self.views) * 100
        )


@python_2_unicode_compatible
class PromoImpressions(BaseImpression):

    """
    Track stats around how successful this promo has been.

    Indexed one per promo per day.
    """

    promo = models.ForeignKey(SupporterPromo, related_name='impressions',
                              blank=True, null=True)

    def __str__(self):
        return u'%s on %s' % (self.promo, self.date)


@python_2_unicode_compatible
class ProjectImpressions(BaseImpression):

    """
    Track stats for a specific project and promo.

    Indexed one per project per promo per day
    """

    promo = models.ForeignKey(SupporterPromo, related_name='project_impressions',
                              blank=True, null=True)
    project = models.ForeignKey(Project, related_name='impressions',
                                blank=True, null=True)

    class Meta(object):
        unique_together = ('project', 'promo', 'date')

    def __str__(self):
        return u'%s / %s on %s' % (self.promo, self.project, self.date)


@python_2_unicode_compatible
class Country(models.Model):
    country = CountryField(unique=True)

    def __str__(self):
        return six.text_type(self.country.name)


@python_2_unicode_compatible
class GeoFilter(models.Model):
    promo = models.ForeignKey(SupporterPromo, related_name='geo_filters',
                              blank=True, null=True)
    filter_type = models.CharField(_('Filter Type'), max_length=20,
                                   choices=FILTER_CHOICES, default='')
    countries = models.ManyToManyField(Country, related_name='filters')

    @property
    def codes(self):
        ret = []
        for wrapped_code in self.countries.values_list('country'):
            ret.append(wrapped_code[0])
        return ret

    def __str__(self):
        return u"Filter for {promo} that {type}s: {countries}".format(
            promo=self.promo.name, type=self.filter_type, countries=self.codes)

docs-erp/readthedocs/donate/templates/donate/create.html
{% extends "base.html" %}

{% load i18n %}
{% load static %}

{% block title %}{% trans "Sustainability" %}{% endblock %}

{% block extra_links %}
  <link rel="stylesheet" href="{% static 'payments/css/form.css' %}" />
{% endblock %}

{% block extra_scripts %}
  <script src="https://js.stripe.com/v2/" type="text/javascript"></script>
  <script type="text/javascript" src="{% static 'vendor/knockout.js' %}"></script>
  <script type="text/javascript" src="{% static 'donate/js/donate.js' %}"></script>
  <script type="text/javascript">
var donate_views = require('donate/donate');
$(document).ready(function () {
    var key;
    //<![CDATA[
    key = '{{ stripe_publishable }}';
    //]]>

    var view = donate_views.DonateView.init({
      key: key,
      form: $('form#donate-payment')
    });
});
  </script>
{% endblock %}


{% block content %}
  <h2>Donate to Read the Docs</h2>

  <p>
    Contributions will be listed on our donation page, with your name and
    photo (from Gravatar). You can choose to donate privately if you do not wish to be listed.
    We do not store your credit card details,
    payment is processed directly through <a href="https://stripe.com">Stripe</a>.
  </p>

  <form action="" method="post" id="donate-payment" class="payment">
    {% csrf_token %}

    {{ form.non_field_errors }}

    {% for field in form.fields_with_cc_group %}
      {% if field.is_cc_group %}
        <div class="subscription-card">
          {% for groupfield in field.fields %}
            {% include 'core/ko_form_field.html' with field=groupfield %}
          {% endfor %}
        </div>
      {% elif field.name == 'logo_url' or field.name == 'site_url' %}
        <div data-bind="visible: urls_enabled">
          {% include 'core/ko_form_field.html' with field=field %}
        </div>
      {% elif field.name == 'dollars' %}
        {{ field.errors }}
        <p>
          <label for="{{ field.id_for_label }}">{{ field.label }}</label>
          <input
              type="hidden"
              name="{{ field.name }}"
              id="{{ field.id_for_label }}"
              data-bind="value: dollars" />
          <input
              type="number"
              data-bind="textInput: dollars_input, visible: dollars_select() == 'custom'"
              value="50"
              id="id_dollars_input"
              style="display: none;" />
          <select data-bind="value: dollars_select, visible: dollars_select() != 'custom'">
            <option value="custom">{% trans "Custom amount" %}</option>
            <option value="5">$5</option>
            <option value="10">$10</option>
            <option value="25">$25</option>
            <option value="50" selected>{% trans "1 Hour" %} ($50)</option>
            <option value="100">{% trans "2 Hours" %} ($100)</option>
            <option value="200">{% trans "4 Hours" %} ($200)</option>
            <option value="400">{% trans "1 Day" %} ($400)</option>
            <option value="800">{% trans "2 Days" %} ($800)</option>
            <option value="1200">{% trans "3 Days" %} ($1200)</option>
            <option value="1600">{% trans "4 Days" %} ($1600)</option>
            <option value="2000">{% trans "5 Days" %} ($2000)</option>
            <option value="4000">{% trans "2 Weeks" %} ($4000)</option>
            <option value="6000">{% trans "3 Weeks" %} ($6000)</option>
            <option value="8000">{% trans "4 Weeks" %} ($8000)</option>
          </select>
          {% if field.help_text %}
            <span class="helptext">{{ field.help_text }}</span>
          {% endif %}
        </p>
      {% else %}
        {% include 'core/ko_form_field.html' with field=field %}
      {% endif %}
    {% endfor %}

    {% trans "Donate" as form_submit_text %}
    <input type="submit" value="{{ form_submit_text }}" data-bind="click: process_form" />
  </form>
{% endblock %}

docs-erp/readthedocs/donate/templates/donate/ethicalads-success.html
{% extends "base.html" %}

{% load i18n %}
{% load static %}

{% block title %}{% trans "Sponsorship" %}{% endblock %}

{% block content %}
  <h2>Thanks for your support</h2>

  <p>
    We think that our <a href="http://docs.readthedocs.io/en/latest/ethical-advertising.html">Ethical Advertising</a> campaign is a wonderful step forward for running ads on open source projects.
    Thanks for your support.
  </p>
{% endblock %}

docs-erp/readthedocs/donate/templates/donate/ethicalads.html
{% extends "base.html" %}

{% load i18n %}
{% load static %}

{% block title %}{% trans "Pay for your ad" %}{% endblock %}

{% block extra_links %}
  <link rel="stylesheet" href="{% static 'payments/css/form.css' %}" />
{% endblock %}

{% block extra_scripts %}
  <script src="https://js.stripe.com/v2/" type="text/javascript"></script>
  <script type="text/javascript" src="{% static 'vendor/knockout.js' %}"></script>
  <script type="text/javascript" src="{% static 'donate/js/donate.js' %}"></script>
  <script type="text/javascript">
var donate_views = require('donate/donate');
$(document).ready(function () {
    var key;
    //<![CDATA[
    key = '{{ stripe_publishable }}';
    //]]>

    var view = donate_views.DonateView.init({
      key: key,
      form: $('form#donate-payment')
    });
});
  </script>
{% endblock %}


{% block content %}
  <h2>Pay for your Sponsorship</h2>

  <p>
    This form can be used to pay for your sponsorship of Read the Docs.
    We think that our <a href="http://docs.readthedocs.io/en/latest/ethical-advertising.html">Ethical Advertising</a> campaign is a wonderful step forward for running ads on open source projects.
    You can pay for these ads below.
  </p>

  <form action="" method="post" id="donate-payment" class="payment">
    {% csrf_token %}

    {{ form.non_field_errors }}

    {% for field in form.fields_with_cc_group %}
      {% if field.is_cc_group %}
        <div class="subscription-card">
          {% for groupfield in field.fields %}
            {% include 'core/ko_form_field.html' with field=groupfield %}
          {% endfor %}
        </div>
      {% elif field.name == 'dollars' %}
        {{ field.errors }}
        <p>
          <label for="{{ field.id_for_label }}">{{ field.label }}</label>
          <input
              type="hidden"
              name="{{ field.name }}"
              id="{{ field.id_for_label }}"
              data-bind="value: dollars" />
          <input
              type="number"
              data-bind="textInput: dollars_input, visible: dollars_select() == 'custom'"
              value="50"
              id="id_dollars_input"
              style="display: none;" />
          <select data-bind="value: dollars_select, visible: dollars_select() != 'custom'">
            <option value="custom">{% trans "Custom amount" %}</option>
            <option value="2000">$2,000</option>
            <option value="3000">$3,000</option>
            <option value="5000" selected>$5,000</option>
            <option value="10000">$10,000</option>
          </select>
          {% if field.help_text %}
            <span class="helptext">{{ field.help_text }}</span>
          {% endif %}
        </p>
      {% else %}
        {% include 'core/ko_form_field.html' with field=field %}
      {% endif %}
    {% endfor %}

    {% trans "Pay" as form_submit_text %}
    <input type="submit" value="{{ form_submit_text }}" data-bind="click: process_form" />
    <p>
    We do not store your credit card details,
    payment is processed directly through <a href="https://stripe.com">Stripe</a>.
    </p>
  </form>
{% endblock %}

docs-erp/readthedocs/donate/templates/donate/progress.html
{% load i18n %}

<div class="donate-stats">
  <h2>Help Support Read the Docs</h2>

  <div class="donate-stats-lg">
    <p>
      Since its inception over four years ago, Read the Docs has grown
      into a massive resource that developers rely on daily.  To
      make Read the Docs <b>sustainable</b>, and to
      improve support for our users and readers, we are asking the community
      for contributions.
    </p>
    <p>
      <b>
        If you consider Read the Docs to be a useful service, and would
        like to see it continue to grow, <b>consider pitching in</b> to
        help cover the cost of bringing free and open documentation to
        everyone.
      </b>
    </p>

    {% if read_more %}
      <p>
        <b><a href="{% url 'donate' %}#about">{% trans 'Read More' %}</a></b>
      </p>
    {% endif %}
  </div>

  <div class="donate-stats-sm">
    <ul>
      {% if not done and not evergreen %}
        <li>
          <div class="donate-progress">
            <div class="donate-progress-inner" style="width: {% if donate_percent > 100 %}100{% else %}{{ donate_percent }}{% endif %}%;">
            </div>
          </div>
        </li>
      {% endif %}
      {% if not evergreen %}
        <li><b>{{ donate_percent }}%</b> funded</li>
        <li><b>${{ donate_amount }}</b> contributed to $24,000 goal</li>
      {% else %}
        <li><b>${{ donate_amount }}</b> contributed</li>
      {% endif %}
      <li><b>${{ donate_avg }}</b> average contribution</li>
      <li><b>{{ donate_count }}</b> <a href="{% url 'donate' %}#supporters">Supporters</a></li>
    </ul>

    {% if not read_more %}
      <form action="{% url 'donate_add' %}" method="get" class="donate-form">
        <select id="id_dollars" name="dollars">
          <option value="5">$5</option>
          <option value="10">$10</option>
          <option value="25">$25</option>
          <option value="50" selected="selected">1 Hour ($50)</option>
          <option value="100">2 Hours ($100)</option>
          <option value="200">4 Hours ($200)</option>
          <option value="400">1 Day ($400)</option>
          <option value="800">2 Days ($800)</option>
          <option value="2000">5 Days ($2000)</option>
        </select>
        <button>{% trans 'Donate Now' %}</button>
      </form>
    {% endif %}
  </div>

</div>

docs-erp/readthedocs/donate/templates/donate/promo_404.html
{% extends "base.html" %}
{% load core_tags %}
{% load static i18n %}

{% block title %}
  {% trans "Maze Found" %}
{% endblock %}

{% block header-wrapper %}
  {% include "error_header.html" %}
{% endblock %}

{% block extra_links %}
  <link rel="stylesheet" href="{% static 'donate/css/donate.css' %}" />
{% endblock %}

{% block content %}
<div id="promo_404">
    {% if suggestion %}
      <div class="suggestions">
          <h1>You've found something that doesn't exist.</h1>
          <p>{{ suggestion.message }}</p>
          {% ifequal suggestion.type 'top' %}
          <p>
              <a href="{{ suggestion.href }}">Go to the top of the documentation.</a>
          </p>
          {% endifequal %}
          {% ifequal suggestion.type 'list' %}
          <ul>
            {% for item in suggestion.list %}
              <li><a href="{% doc_url item.project item.version_slug item.pagename %}">{{ item.label }}</a></li>
            {% endfor %}
          </ul>
          {% endifequal %}
      </div>
    {% endif %}

<h1>
Page Not Found!
</h1>

<a href="{{ promo_data.link }}">
  <img src="{{ promo_data.image }}" width="75%" />
</a>

<p>
Read the Docs is sponsored by <a href="{{ promo_data.link }}">Sentry</a>, which gives developers the tools to keep calm when things catch fire.
</p>
</div>
{% endblock %}

docs-erp/readthedocs/donate/templates/donate/promo_detail.html
{% extends "base.html" %}

{% load i18n %}
{% load static %}

{% block title %}{% trans "Promo Detail" %}{% endblock %}

{% block extra_links %}
  <link rel="stylesheet" href="{% static 'donate/css/donate.css' %}" />
{% endblock %}

{% block content %}

<h1> Promo Results </h1>

{% if promos %}

{% if promos|length > 1 %}
<p>
<strong>Total Clicks for all shown promos</strong>: {{ total_clicks }}
</p>
{% endif %}

<div id="promo_detail">
{% for promo in promos %}

<h3>
Results for {{ promo.name }} ({{ promo.analytics_id }}) over last {{ days }} days.
</h3>

<div class="example">

  <div class="filters">
    {% if promo.programming_language %}
      <dl>
        <dt>Filtered Language</dt>
        <dd>{{ promo.programming_language }}</dd>
      </dl>
    {% endif %}

    {% if promo.geo_filters.count %}
      <dl>
        <dt>Filtered Geos</dt>
        {% for geo in promo.geo_filters.all %}
          <dd>
          {{ geo.get_filter_type_display }}: {{ geo.countries.all|join:", " }}
          </dd>
        {% endfor %}
      </dl>
    {% endif %}

    {% if promo.sold_clicks %}
      <dl>
        <dt>Total Clicks Sold</dt>
        <dd>
        {{ promo.sold_clicks }}
        </dd>
      </dl>
    {% endif %}
  </div>


  <div class="promo">
    <div id="promo_image">
      <a href="{{ promo.link }}">
        <img width=120 height=90 src="{{ promo.image }}">
      </a>
    </div>

    <div id="promo_text">
      {{ promo.report_html_text|safe }}
    </div>
  </div>

</div>

<h5>Promo Data</h5>
<table>
  <tr>
    <th><strong>Day (UTC)</strong></th>
    <th><strong>Views</strong></th> 
    <th><strong>Clicks</strong></th>
    <th><strong>CTR</strong></th>
  </tr>
  {% for day in promo.impressions.all|slice:days_slice %}
  {% if day.views > 0 %}
  <tr>
    <td>{{ day.date }}</td>
    <td><code>{{ day.views }}</code></td> 
    <td><code>{{ day.clicks }}</code></td>
    <td><code>{{ day.click_ratio }}%</code></td>
  </tr>
  {% endif %}
  {% endfor %}
  <tr>
    <td><strong>Total (over all time)</strong> </td>
    <td><strong>{{ promo.total_views }}</strong></td> 
    <td><strong>{{ promo.total_clicks }}</strong></td>
    <td><strong>{{ promo.total_click_ratio }}%</strong></td>
  </tr>
</table>

{% endfor %}
</div>

{% else %}

No promos match this query.

{% endif %}

{% endblock %}